### ISSUE TITLE
Task not serializable

### ISSUE THREAD

**Issue by dzqoo** [BenFradet/spark-kafka-writer#141]
when I use RDDKafkaWriter，I got the flowwing error：
Exception in thread "main" org.apache.spark.SparkException: Task not serializable
	at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:345)
	at org.apache.spark.util.ClosureCleaner$.org$apache$spark$util$ClosureCleaner$$clean(ClosureCleaner.scala:335)
	at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:159)
	at org.apache.spark.SparkContext.clean(SparkContext.scala:2299)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:928)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:927)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
	at org.apache.spark.rdd.RDD.foreachPartition(RDD.scala:927)
here are my code：
 val conf = new SparkConf()
    conf.set("spark.serializer", "org.apache.spark.serializer.KryoSerializer")
    conf.set("spark.io.compression.codec", "snappy")
    val spark = SparkSession
      .builder()
      .config(conf)
      .appName(s"***")
      .getOrCreate()

    val ansRecordDF = spark.read.parquet(config.appInputPath())
    import spark.implicits._
    val kafkaSession:Dataset[KafkaSession] = ansRecordDF.rdd.flatMap(record =>{
      ...
      Iterable(KafkaSession(userid,topic_id,subjectCode,score,standardscore,gradecode,catalogcode,anchorid,timestamp))
    }).toDF().as[KafkaSession]

    kafkaSession.writeToKafka(
      producerConfig,
      KafkaSession => new ProducerRecord[String, String](config.kafkaTopic(), KafkaSession.toString)
    )
Would you mind giving me a solution？Thank you.

**Comment by BenFradet** [comment]
Do you have the full stack trace? Usually it points to where in the code the problem is at the end.

Also, does it produce the same issue when writing the data to a file, for example?

**Comment by dzqoo** [comment]
Here are the full stack trace：
Exception in thread "main" org.apache.spark.SparkException: Task not serializable
	at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:345)
	at org.apache.spark.util.ClosureCleaner$.org$apache$spark$util$ClosureCleaner$$clean(ClosureCleaner.scala:335)
	at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:159)
	at org.apache.spark.SparkContext.clean(SparkContext.scala:2299)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:928)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:927)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
	at org.apache.spark.rdd.RDD.foreachPartition(RDD.scala:927)
	at org.iflytek.odeon.enigma.test.spark.kafka.writer.RDDKafkaWriter.writeToKafka(RDDKafkaWriter.scala:29)
	at org.iflytek.odeon.enigma.test.spark.kafka.writer.DatasetKafkaWriter.writeToKafka(DatasetKafkaWriter.scala:47)
	at org.iflytek.odeon.enigma.test.File2Kafka$.main(File2Kafka.scala:63)
	at org.iflytek.odeon.enigma.test.File2Kafka.main(File2Kafka.scala)
I can slove the problem by defining ProducerRecord in the exector.Here are my code:
class RDDKafkaWriter[T: ClassTag](@transient private val rdd: RDD[T])
  extends KafkaWriter[T] with Serializable {

  /**
    * Write a [[RDD]] to Kafka
    *
    * @param producerConfig producer configuration for creating KafkaProducer
    * @param transformFunc  a function used to transform values of T type into [[ProducerRecord]]s
    * @param callback       an optional [[Callback]] to be called after each write, default value is None.
    */

  override def writeToKafka[K, V](
                                       producerConfig: Map[String, Object],
                                       transformFunc: T => ProducerRecord[K, V],
                                       callback: Option[Callback] = None
                                     ): Unit =
    rdd.foreachPartition { partition =>
      val producer = KafkaProducerCache.getProducer[String, String](producerConfig)
      partition
        .map(x=>new ProducerRecord[String,String]("test", x.toString))//here is where my code
        .foreach(record => producer.send(record, callback.orNull))
    }
}

**Comment by dzqoo** [comment]
I know where I was wrong！
Thank you very much
