### ISSUE TITLE
Bump to spark 2.1.0

### ISSUE THREAD

**Issue by BenFradet** [BenFradet/spark-kafka-writer#37]

**Comment by phungleson** [comment]
I am keen to take a look into this, wonder if you foresee any issues?

Do we just upgrade and make sure tests pass or do we need to check anything else?

**Comment by BenFradet** [comment]
Yup, it should just be a matter of upgrading and running the tests.

**Comment by phungleson** [comment]
When I run `sbt test` I got this error even though I have nothing on 2181 nor 9092.

Any suggestions?

```
[info] RDDKafkaWriterSpec:
[info] Exception encountered when attempting to run a suite with class name: com.github.benfradet.spark.kafka010.writer.RDDKafkaWriterSpec *** ABORTED ***
[info]   java.net.BindException: Address already in use
[info]   at sun.nio.ch.Net.bind0(Native Method)
[info]   at sun.nio.ch.Net.bind(Net.java:436)
[info]   at sun.nio.ch.Net.bind(Net.java:428)
[info]   at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214)
[info]   at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
[info]   at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:67)
[info]   at org.apache.zookeeper.server.NIOServerCnxnFactory.configure(NIOServerCnxnFactory.java:95)
[info]   at com.github.benfradet.spark.kafka010.writer.KafkaTestUtils$EmbeddedZookeeper.<init>(KafkaTestUtils.scala:169)
[info]   at com.github.benfradet.spark.kafka010.writer.KafkaTestUtils.setupEmbeddedZookeeper(KafkaTestUtils.scala:80)
[info]   at com.github.benfradet.spark.kafka010.writer.KafkaTestUtils.setup(KafkaTestUtils.scala:75)
```

**Comment by BenFradet** [comment]
This might have been cause by @c27a830bc4689f908cfe62033c4fa332468b4c92 or @79a590ee31577ad455ec7526f533f06a8f196ec4 .

Although it's weird that the ci passed for those commits.
