### ISSUE TITLE
Make the API more Java friendly

### ISSUE THREAD

**Issue by BenFradet** [BenFradet/spark-kafka-writer#59]

**Comment by huylv** [comment]
Hi Ben. Can I use this lib in Java at the moment?

**Comment by BenFradet** [comment]
It should be possible instantiating your own `Function1` like:

```java
Function1<String, ProducerRecord<String, String>> f = new AbstractFunction1<String, ProducerRecord<String, String>() {
    public ProducerRecord<String, String> apply(String s) {
        return new ProducerRecord<String, String>(topic, s);
    }
};
```

but I think it's a bit clumsy that's why I want to provide an API which is more java friendly.

**Comment by huylv** [comment]
How do I call the `writeToKafka()` function? I need to write a `JavaDStream` to Kafka.

**Comment by BenFradet** [comment]
My bad didn't take into account the fact that you had a `JavaDStream`.

Can't you call [`dstream`](http://spark.apache.org/docs/latest/api/java/org/apache/spark/streaming/api/java/JavaDStream.html#dstream()) on your `JavaDStream`?

and then `writeToKafka`?

**Comment by huylv** [comment]
I can call `dstream` from `JavaDStream`, but it doesn't provide `.writeToKafka()` function.

**Comment by BenFradet** [comment]
True, forgot about the implicits and Java.

You might want to try:

```java
import static com.github.benfradet.spark.kafka010.write.dStreamToKafkaWriter
KafkaWriter<String> w = dStreamToKafkaWriter<String, String, String>(javaDStream.dStream());
w.writeToKafka(...);
```

**Comment by huylv** [comment]
This is the code I write. However, it looks like `Function1` is not serializable:

    Properties props = new Properties();
    props.put("bootstrap.servers", "localhost:9092");
    props.put("value.serializer", StringSerializer.class);

    KafkaWriter<String> kafkaWriter = new DStreamKafkaWriter<>(myStream.dstream(), scala.reflect.ClassTag$.MODULE$.apply(String.class));
    Function1<String, ProducerRecord<String, String>> f = new AbstractFunction1<String, ProducerRecord<String, String>>() {
        @Override
        public ProducerRecord<String, String> apply(final String s) {
            return new ProducerRecord<>("my-topic", s);
        }
    };
    kafkaWriter.writeToKafka(props, f, Option.empty());

Here's the serialization stack trace:

    Serialization stack:
        - object not serializable (class: Main$1, value: <function1>)
        - field (class: com.github.benfradet.spark.kafka010.writer.RDDKafkaWriter$$anonfun$writeToKafka$1, name: transformFunc$1, type: interface scala.Function1)
        - object (class com.github.benfradet.spark.kafka010.writer.RDDKafkaWriter$$anonfun$writeToKafka$1, <function1>)
        at org.apache.spark.serializer.SerializationDebugger$.improveException(SerializationDebugger.scala:40)
        at org.apache.spark.serializer.JavaSerializationStream.writeObject(JavaSerializer.scala:46)
        at org.apache.spark.serializer.JavaSerializerInstance.serialize(JavaSerializer.scala:100)
        at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:295)
        ... 31 more

**Comment by BenFradet** [comment]
Have you tried having `AbstractFunction1` extend `Serializable`:

```java
Function1<String, ProducerRecord<String, String>> f = new AbstractFunction1<String, ProducerRecord<String, String>>() extends Serializable {
        @Override
        public ProducerRecord<String, String> apply(final String s) {
            return new ProducerRecord<>("my-topic", s);
        }
    };
```

?

**Comment by huylv** [comment]
Hey, thanks. It works know. I'll leave here my complete code with correct Java syntax for anyone who's interested in:

```java    
    abstract class MyFunc<T, U> extends AbstractFunction1<T, U> implements Serializable {}

    public static void main(String[] args) {
    Properties props = new Properties();
        props.put("bootstrap.servers", "localhost:9092");
        props.put("value.serializer", StringSerializer.class);

        KafkaWriter<String> kafkaWriter = new DStreamKafkaWriter<>(myStream.dstream(), scala.reflect.ClassTag$.MODULE$.apply(String.class));
        Function1<String, ProducerRecord<String, String>> f = new MyFunc<String, ProducerRecord<String, String>>() {
            @Override
            public ProducerRecord<String, String> apply(final String s) {
                return new ProducerRecord<>("my-topic", s);
            }
        };
        kafkaWriter.writeToKafka(props, f, Option.empty());
    }
```

**Comment by BenFradet** [comment]
Great stuff 👍 

Feel free to open a PR adding a section in the readme with your code

**Comment by huylv** [comment]
I've created pull request #60. Please have a look. Thanks.

**Comment by vipin-kumar-tomar** [comment]
Does it take care that ProducerRecord is created only once and used across all executors?

**Comment by BenFradet** [comment]
What do you mean? the procuder record is created in the function `f` so every time a message is sent a new producer record is created.

**Comment by vipin-kumar-tomar** [comment]
It is suggested on most of the links to use a single Producer across all executors. e.g. below link:
http://www.michael-noll.com/blog/2014/10/01/kafka-spark-streaming-integration-example-tutorial/

**Comment by BenFradet** [comment]
Yeah, you wrote:

>Does it take care that __ProducerRecord__ is created only once and used across all executors?

that's what confused me.

To answer your question, only one __Producer__ is created per executor since you can't share them across executors.

**Comment by sunone5** [comment]
@huylv & @BenFradet 
I have tried this Java code with following latest maven artifact.
https://mvnrepository.com/artifact/com.github.benfradet/spark-kafka-writer_2.10/0.4.0
As well as previous one - https://mvnrepository.com/artifact/com.github.benfradet/spark-kafka-writer_2.10/0.1.0
But following code doesn't allow me to compile with Java 1.8 and Eclipse Oxygen latest IDE.
-----------------------------------------IMPORT SECTION-------------------------------------------
import com.github.benfradet.spark.kafka.writer.DStreamKafkaWriter;
import com.github.benfradet.spark.kafka.writer.KafkaWriter;
import org.apache.kafka.common.serialization.StringSerializer;
import scala.Function1;
import scala.Option;
import scala.Serializable;
--------------------------------------------------------------------------------------------------------
Properties props = new Properties();
	        props.put("bootstrap.servers", "localhost:9092");
	        props.put("key.serializer", StringSerializer.class);
	        props.put("value.serializer", StringSerializer.class);
	        
	        Map<String, Object> producerConfig = new HashMap<String, Object>();
	        producerConfig.put("bootstrap.servers", "localhost:9092");
	        producerConfig.put("key.serializer", StringSerializer.class);
	        producerConfig.put("value.serializer", StringSerializer.class);
	        
	        KafkaWriter<String> kafkaWriter = new DStreamKafkaWriter<>(lines.dstream(), scala.reflect.ClassTag$.MODULE$.apply(String.class));

	        Function1<String, ProducerRecord<String, String>> f = new MyFunc<String, ProducerRecord<String, String>>() {
	            @Override
	            public ProducerRecord<String, String> apply(final String s) {
	                return new ProducerRecord<>("my-topic", s);
	            }
	        };
	        
	        kafkaWriter.writeToKafka(producerConfig, f,Option.empty());
-----------------------------------------------------------------------------------------------------------

KafkaWriter.writerToKafka(producerConfig,f,Option.empty)  --- Line gives me a following Error on Eclipse IDE
![image](https://user-images.githubusercontent.com/4546194/31063550-bb9667a0-a751-11e7-9d2e-e3e9a5594310.png)

Any help appreciate.

**Comment by BenFradet** [comment]
You need to turn your java map into a scala one:

```java
import scala.collection.JavaConverters._
// ...
kafkaWriter.writeToKafka(producerConfig.asScala, f,Option.empty());
```

**Comment by rfmvlc** [comment]
Hello Ben,

It doesn't work on Java RDDs? -> @BenFradet work on JavaDStream..

Cheers!
