### ISSUE TITLE
Closing / stopping the publisher for tests

### ISSUE THREAD

**Issue by timgentonzo** [BenFradet/spark-kafka-writer#90]
Thanks for the great library :)

I've written a test for a method that is writing an RDD to Kafka. At the end of the test the embedded Kafka and Zookeeper are shut down, as are my test consumer and my connection to zookeeper (just used for creating the topic).

However I can't find a way to stop the producer trying to connect to Kafka once the test is over, resulting in lots of the following exceptions being created in rapid succession. The only way to stop these is then to terminate sbt:
```
10:50:02.728 [kafka-producer-network-thread | producer-1] DEBUG org.apache.kafka.clients.NetworkClient - Initialize connection to node localhost:9092 (id: 0 rack: null) for sending metadata request
10:50:02.728 [kafka-producer-network-thread | producer-1] DEBUG org.apache.kafka.clients.NetworkClient - Initiating connection to node localhost:9092 (id: 0 rack: null)
10:50:02.728 [kafka-producer-network-thread | producer-1] DEBUG org.apache.kafka.common.network.Selector - Connection with localhost/127.0.0.1 disconnected
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.kafka.common.network.PlaintextTransportLayer.finishConnect(PlaintextTransportLayer.java:50)
	at org.apache.kafka.common.network.KafkaChannel.finishConnect(KafkaChannel.java:95)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:361)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:326)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:433)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:224)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:162)
	at java.lang.Thread.run(Thread.java:748)
10:50:02.728 [kafka-producer-network-thread | producer-1] DEBUG org.apache.kafka.clients.NetworkClient - Node 0 disconnected.
10:50:02.728 [kafka-producer-network-thread | producer-1] WARN org.apache.kafka.clients.NetworkClient - Connection to node 0 could not be established. Broker may not be available.
10:50:02.728 [kafka-producer-network-thread | producer-1] DEBUG org.apache.kafka.clients.NetworkClient - Give up sending metadata request since no node is available
```

**Comment by timgentonzo** [comment]
Sorry just realised you do expose this....
KafkaProducerCache.close(producerConfig)
